//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEPSEntities : DbContext
    {
        public DBEPSEntities()
            : base("name=DBEPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Categories> TB_Categories { get; set; }
        public virtual DbSet<TB_Groups> TB_Groups { get; set; }
        public virtual DbSet<TB_Users> TB_Users { get; set; }
        public virtual DbSet<TB_Note> TB_Note { get; set; }
        public virtual DbSet<TB_SystemLogs> TB_SystemLogs { get; set; }
        public virtual DbSet<TB_Suppliers> TB_Suppliers { get; set; }
        public virtual DbSet<TB_Buy> TB_Buy { get; set; }
        public virtual DbSet<TB_Customers> TB_Customers { get; set; }
        public virtual DbSet<TB_Sell> TB_Sell { get; set; }
        public virtual DbSet<TB_SellData> TB_SellData { get; set; }
        public virtual DbSet<TB_ABC> TB_ABC { get; set; }
        public virtual DbSet<TB_Pyments> TB_Pyments { get; set; }
        public virtual DbSet<TB_CustomerPaymentLogs> TB_CustomerPaymentLogs { get; set; }
        public virtual DbSet<TB_Paymentsbuy> TB_Paymentsbuy { get; set; }
        public virtual DbSet<TB_SuppliersPayments> TB_SuppliersPayments { get; set; }
        public virtual DbSet<TBL_ACTIVE> TBL_ACTIVE { get; set; }
    }
}
