//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ABC
    {
        public int ID { get; set; }
        public byte[] A { get; set; }
        public byte[] B { get; set; }
        public byte[] C { get; set; }
        public byte[] D { get; set; }
        public byte[] E { get; set; }
    }
}
