//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Customers()
        {
            this.TB_Sell = new HashSet<TB_Sell>();
        }
    
        public int ID { get; set; }
        public string SupplierName { get; set; }
        public Nullable<double> SupplierBalance { get; set; }
        public Nullable<double> SupplierPhone { get; set; }
        public string SupplierAddress { get; set; }
        public Nullable<System.DateTime> SupplierDate { get; set; }
        public Nullable<double> SupplierBalanceprim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Sell> TB_Sell { get; set; }
    }
}
