//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Note
    {
        public int ID { get; set; }
        public string NoteDes { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string NoteManger { get; set; }
        public string NoteUser { get; set; }
        public string NoteType { get; set; }
    }
}
