//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pyments
    {
        public int ID { get; set; }
        public Nullable<int> IDSELL { get; set; }
        public string CustomerName { get; set; }
        public Nullable<double> Paymentone { get; set; }
        public Nullable<double> Paymenttwo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<double> CurrentPaymentone { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string PaymentState { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string colone { get; set; }
        public string coltwo { get; set; }
        public string colthree { get; set; }
        public string colfour { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public string SellName { get; set; }
    
        public virtual TB_Sell TB_Sell { get; set; }
    }
}
