//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SellData
    {
        public int ID { get; set; }
        public Nullable<int> IDSell { get; set; }
        public string MatrialsName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string CustomerName { get; set; }
        public string SellState { get; set; }
        public Nullable<double> SellValue { get; set; }
        public Nullable<double> SellAllValue { get; set; }
        public Nullable<double> CustomerBalance { get; set; }
        public Nullable<double> CustomerBalanceprim { get; set; }
    
        public virtual TB_Sell TB_Sell { get; set; }
    }
}
