//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Sell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Sell()
        {
            this.TB_SellData = new HashSet<TB_SellData>();
            this.TB_Pyments = new HashSet<TB_Pyments>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public string CustomerName { get; set; }
        public Nullable<double> CustomerBalance { get; set; }
        public Nullable<double> SellValue { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Barcode { get; set; }
        public byte[] BarcodeImage { get; set; }
        public string SellMenuName { get; set; }
        public Nullable<double> CustomerBalanceprim { get; set; }
    
        public virtual TB_Customers TB_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SellData> TB_SellData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Pyments> TB_Pyments { get; set; }
    }
}
