//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SuppliersPayments
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> SellID { get; set; }
        public Nullable<double> Pamnent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> colone { get; set; }
        public string coltow { get; set; }
        public string colthreee { get; set; }
    }
}
