//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ACTIVE
    {
        public string MAC_ADDRESS { get; set; }
        public Nullable<System.DateTime> ADD_DATE { get; set; }
        public string ACTIVE_KEY { get; set; }
        public Nullable<System.DateTime> ACTIVE_DATE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
