using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace EPS.BL
{
    public partial class Pymnetsrequired : DevExpress.XtraEditors.XtraForm
    {
        private string valuePayment;

        DBEPSEntities db;
        TB_Pyments add;
        public int id;

        public Pymnetsrequired()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
        }

        private void LoadData()
        {
            EPS.DBEPSEntities dbContext = new EPS.DBEPSEntities();
            gridControl1.DataSource = dbContext.TB_Pyments.Where(x => x.PaymentState=="لا" || x.PaymentState == "جزء").ToList();
            SetPaymnetSum();
        }
        private void btn_payment_Click(object sender, EventArgs e)
        {
            try
            {
                var primerycurrname = Properties.Settings.Default.PrimaryCurrName;
                var paymnetsvalue = Convert.ToString(gridView1.GetFocusedRowCellValue("Paymentone"));
                var paymnetsvalue2 = Convert.ToString(gridView1.GetFocusedRowCellValue("CurrentPaymentone"));
                var paymentret = Convert.ToDouble(paymnetsvalue) - Convert.ToDouble(paymnetsvalue2);


                valuePayment = XtraInputBox.Show("اكتب المبلغ المراد دفعة في عملة " + "[" + primerycurrname + "],تذكر سيتم التسديد هنا وفي بيانات العميل ", "عمل دفعة", paymentret.ToString());




                if (valuePayment != null && Convert.ToDouble(valuePayment) <= Convert.ToDouble(paymentret))
                {
                    MakePayment();
                    LoadData();
                }
                else
                {
                    MessageBox.Show("يجب ان لا تكون قيمة الدفعة اكبر من المستحقة");
                }
            }
            catch { }
         
        }


        private void MakePayment()
        {
            

            try
            {
                db = new DBEPSEntities();
                add = new TB_Pyments();
                id = Convert.ToInt16(gridView1.GetFocusedRowCellValue("ID"));
                add = db.TB_Pyments.Where(x => x.ID == id).FirstOrDefault();

                if (id != 0)
                {

                    if (add.CurrentPaymentone == null)
                    {
                        add.CurrentPaymentone = 0;
                    }
                    add.CurrentPaymentone = add.CurrentPaymentone+Convert.ToDouble(valuePayment);
                    add.CurrentDate = DateTime.Now;
                    if (add.Paymentone <= add.CurrentPaymentone)
                    {
                        add.PaymentState = "نعم";

                    }
                    else if (add.CurrentPaymentone == 0)
                    {
                        add.PaymentState = "لا";

                    }
                    else
                    {
                        add.PaymentState = "جزء";

                    }
                    TB_CustomerPaymentLogs logs = new TB_CustomerPaymentLogs
                    {
                        SellID = add.IDSELL,
                        CustomerID = add.IDCustomer,
                        Pamnent = Convert.ToDouble(valuePayment),
                        Date = DateTime.Now
                    };
                    db.TB_CustomerPaymentLogs.Add(logs);
                    db.Entry(add).State = System.Data.Entity.EntityState.Modified;
                    // Save DataBase
                    db.SaveChanges();
                    toastNotificationsManager1.ShowNotification("f1449fe1-3838-416b-b71a-c50500f603ee");
                }
                else
                {
                    MessageBox.Show("لا يوجد بيانات , اختر صف لعمل الدفعة", "لا يمكن اجراء العملية", MessageBoxButtons.OK, MessageBoxIcon.Information);

                }

            }
            catch
            {

            }
        }

        private void Pymnets_Load(object sender, EventArgs e)
        {
            LoadData();          
        }
        private void SetPaymnetSum()
        {
            try
            {
                db = new DBEPSEntities();
                
                var listpayments1 = db.TB_Pyments.Select(x => x.CurrentPaymentone).ToArray().Sum();
                var listpayments2 = db.TB_Pyments.Select(x => x.Paymentone).ToArray().Sum();
                var credit = listpayments2 - listpayments1;
                lb_creditreq.Text = listpayments2.ToString();
                lb_creditpay.Text = listpayments1.ToString();
                lb_credit.Text = credit.ToString();
            }
            catch(Exception ex) { MessageBox.Show(ex.Message); }
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
          
        }

        private void btn_showdateoflogs_Click(object sender, EventArgs e)
        {
            try
            {
                id = Convert.ToInt16(gridView1.GetFocusedRowCellValue("ID"));
                add = db.TB_Pyments.Where(x => x.ID == id).FirstOrDefault();
                id = Convert.ToInt32(add.IDCustomer);
                db = new DBEPSEntities();
                FRM_PamymnetsLogs logs = new FRM_PamymnetsLogs();
                logs.Text = logs.Text + " - اسم العميل " + add.CustomerName;
                logs.gridControl1.DataSource = db.TB_CustomerPaymentLogs.Where(x => x.CustomerID == id).ToList();
                logs.Show();
            }
            catch { }

        }
    }
}